name: Deploy to Linux Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Copy Files to Server
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
        rsync -avz --exclude=".git/" ./ $SSH_USERNAME@$SSH_HOST:$DEPLOY_PATH

    - name: Restart Application
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      run: |
        ssh -i ~/.ssh/id_rsa $SSH_USERNAME@$SSH_HOST << EOF
          cd $DEPLOY_PATH
          # Optional: Set up virtual environment and install dependencies
          source venv/bin/activate
          pip install -r requirements.txt
          # Restart the application (modify for your specific server)
          sudo systemctl restart your-app.service
        EOF
